---
- name: add apt-key
  shell:
    sudo apt-key list | grep -qi Elasticsearch
    || wget -qO - http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    | sudo apt-key add -
  register: result
  changed_when: "'OK' in result.stdout"

- name: add apt repository
  copy:
    src=etc/apt/sources.list.d/elasticsearch.list
    dest=/etc/apt/sources.list.d/elasticsearch.list

- name: install depences
  apt:
    update_cache=yes
    pkg={{ item }}
  with_items:
    - openjdk-7-jre-headless
    - elasticsearch
    - python
    - python-pip

- name: install curator
  pip: name=elasticsearch-curator

- name: add curator to cron
  cron:
    name="delete elasticsearch indexes"
    job="/usr/local/bin/curator --host localhost delete --older-than {{ index_lifetime }}"
    hour=0
    minute=20

- name: update-rc.d elasticsearch
  shell:
    update-rc.d elasticsearch defaults 95
    creates=/etc/rc2.d/S95elasticsearch

- name: set elasticsearch config file
  copy:
    src=etc/default/elasticsearch
    dest=/etc/default/elasticsearch
  notify: restart elasticsearch
